# fly.toml app configuration file

# ↓↓↓ たぶん、この行が消えちゃってたんだと思う！ ↓↓↓
app = 'ifindu'
primary_region = 'nrt' # 日本の東京リージョン

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

# データベースを保存するための専用ディスクの設定
[[mounts]]
  source = 'ifindu_data'
  destination = '/data'